[tool.poetry]
name = "waka-readme"
version = "0.1.7"
description = "Wakatime Weekly Metrics on your Profile Readme."
authors = ["Athul Cyriac Ajay <athul8720@gmail.com>"]
license = "MIT"
readme = "README.md"
#packages = [{include = "waka_readme"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
PyGithub = "^1.57"
Faker = "^15.3.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.0"
pylint = "^2.15.7"
python-dotenv = "^0.21.0"
loguru = "^0.6.0"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
