[tool.poetry]
name = "waka-readme"
version = "0.1.6"
description = "Wakatime Weekly Metrics on your Profile Readme."
authors = ["Athul Cyriac Ajay <athul8720@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
PyGithub = "^1.55"
Faker = "^13.16.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
pylint = "^2.15.3"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
