[tool.poetry]
name = "waka-readme"
version = "0.2.0"
description = "Wakatime Weekly Metrics on your Profile Readme."
authors = ["Athul Cyriac Ajay <athul8720@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faker = "^18.6.2"
pygithub = "^1.58.1"
requests = "^2.29.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
bandit = "^1.7.5"
loguru = "^0.7.0"
pylint = "^2.17.3"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
